# Generated by Django 3.1.2 on 2020-12-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20201119_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='choose_us',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
