# Generated by Django 3.1.2 on 2021-01-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0006_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='slug'),
        ),
    ]
