# Generated by Django 3.1.2 on 2020-10-27 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimages',
            options={'verbose_name': 'PropertyImage', 'verbose_name_plural': 'PropertyImages'},
        ),
    ]
