# Generated by Django 3.1.2 on 2020-10-31 02:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20201027_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('date_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_to', models.DateTimeField(default=django.utils.timezone.now)),
                ('guest', models.IntegerField(default=1)),
                ('children', models.IntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_book', to='property.property')),
            ],
        ),
    ]
