# Generated by Django 3.1.2 on 2020-11-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20201101_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
