# Generated by Django 3.1.2 on 2020-11-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20201101_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
