# Generated by Django 3.1.2 on 2020-11-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20201101_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
