# Generated by Django 3.1.2 on 2020-11-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20201104_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
