# Generated by Django 3.1.2 on 2020-12-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20201104_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
