# Generated by Django 3.1.2 on 2021-01-08 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0014_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertybook',
            name='name',
        ),
        migrations.AddField(
            model_name='propertybook',
            name='user_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_book', to='auth.user'),
            preserve_default=False,
        ),
    ]
