# Generated by Django 3.1.2 on 2021-01-09 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_remove_propertybook_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyreview',
            old_name='ratting',
            new_name='rating',
        ),
    ]
