# Generated by Django 3.1.2 on 2021-01-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20210109_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyreview',
            name='feedback',
            field=models.CharField(default='', max_length=500),
        ),
    ]
