# Generated by Django 3.1.2 on 2021-01-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20210109_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyreview',
            name='feedback',
            field=models.TextField(default='', max_length=200),
        ),
    ]
