# Generated by Django 3.1.2 on 2021-01-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_auto_20210109_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
